### ISSUE TITLE
Problem with matching a TGN concept

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#329]
Ran into this while trying to add a match to TGN. Might be a problem in our config or it might be a problem with skosprovider_getty.

```
2016-08-12 16:57:07,631 ERROR [atramhasis.views.exception_views][waitress] 'TGNProvider' object has no attribute 'conceptscheme_id'
Traceback (most recent call last):
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/koen/Virtualenvs/atramhasis/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/koen/Projecten/python/skos/atramhasis/atramhasis/audit.py", line 59, in advice
    response = fn(parent_object, *args, **kw)
  File "/home/koen/Projecten/python/skos/atramhasis/atramhasis/views/views.py", line 145, in concept_view
    c = self.skos_manager.get_thing(c_id, provider.conceptscheme_id)
AttributeError: 'TGNProvider' object has no attribute 'conceptscheme_id'
```

**Comment by koenedaele** [comment]
Not sure how this was possible unless there was a misconfiguration. Can't reproduce at the moment either.

**Comment by koenedaele** [comment]
Check if this can be reproduced, if not close.

**Comment by koenedaele** [comment]
Can't reproduce. Closing as invalid.
