### ISSUE TITLE
Threading issues

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#343]
When launching 4 simultaneous requests for `https://thesaurus.onroerenderfgoed.be/conceptschemes/Materialen/c`, I get the following:

```
[Fri Sep 09 14:08:25 2016] [error] 2016-09-09 14:08:25,004 ERROR [atramhasis.views.exception_views][MainThread] Parent instance <ConceptScheme at 0x7f3fcd55a890> is not bound to a Session; lazy load operation of attribute 'notes' cannot proceed
[Fri Sep 09 14:08:25 2016] [error] Traceback (most recent call last):
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
[Fri Sep 09 14:08:25 2016] [error]     response = handler(request)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 95, in tm_tween
[Fri Sep 09 14:08:25 2016] [error]     reraise(*exc_info)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 76, in tm_tween
[Fri Sep 09 14:08:25 2016] [error]     response = handler(request)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
[Fri Sep 09 14:08:25 2016] [error]     response = view_callable(context, request)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
[Fri Sep 09 14:08:25 2016] [error]     result = view(context, request)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 477, in _class_requestonly_view
[Fri Sep 09 14:08:25 2016] [error]     response = getattr(inst, attr)()
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/atramhasis/views/rdf.py", line 37, in rdf_full_export_turtle
[Fri Sep 09 14:08:25 2016] [error]     graph = utils.rdf_dumper(self.provider)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_rdf/utils.py", line 40, in rdf_dumper
[Fri Sep 09 14:08:25 2016] [error]     return _rdf_dumper(provider, None)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_rdf/utils.py", line 79, in _rdf_dumper
[Fri Sep 09 14:08:25 2016] [error]     c = provider.get_by_id(id)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 183, in go
[Fri Sep 09 14:08:25 2016] [error]     ret = fn(parent_object, *args, **kw)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 184, in get_by_id
[Fri Sep 09 14:08:25 2016] [error]     return self._from_thing(thing)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 156, in _from_thing
[Fri Sep 09 14:08:25 2016] [error]     concept_scheme=self.concept_scheme,
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 97, in concept_scheme
[Fri Sep 09 14:08:25 2016] [error]     return self._get_concept_scheme()
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 183, in go
[Fri Sep 09 14:08:25 2016] [error]     ret = fn(parent_object, *args, **kw)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 118, in _get_concept_scheme
[Fri Sep 09 14:08:25 2016] [error]     for n in csm.notes
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
[Fri Sep 09 14:08:25 2016] [error]     return self.impl.get(instance_state(instance), dict_)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 591, in get
[Fri Sep 09 14:08:25 2016] [error]     value = self.callable_(state, passive)
[Fri Sep 09 14:08:25 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 508, in _load_for_state
[Fri Sep 09 14:08:25 2016] [error]     (orm_util.state_str(state), self.key)
[Fri Sep 09 14:08:25 2016] [error] DetachedInstanceError: Parent instance <ConceptScheme at 0x7f3fcd55a890> is not bound to a Session; lazy load operation of attribute 'notes' cannot proceed
[Fri Sep 09 14:09:20 2016] [error] 2016-09-09 14:09:20,696 ERROR [atramhasis.views.exception_views][Dummy-3] Transaction must be committed using the transaction manager
[Fri Sep 09 14:09:20 2016] [error] Traceback (most recent call last):
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
[Fri Sep 09 14:09:20 2016] [error]     response = handler(request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 95, in tm_tween
[Fri Sep 09 14:09:20 2016] [error]     reraise(*exc_info)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 76, in tm_tween
[Fri Sep 09 14:09:20 2016] [error]     response = handler(request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
[Fri Sep 09 14:09:20 2016] [error]     response = view_callable(context, request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
[Fri Sep 09 14:09:20 2016] [error]     result = view(context, request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 477, in _class_requestonly_view
[Fri Sep 09 14:09:20 2016] [error]     response = getattr(inst, attr)()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/atramhasis/views/rdf.py", line 37, in rdf_full_export_turtle
[Fri Sep 09 14:09:20 2016] [error]     graph = utils.rdf_dumper(self.provider)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_rdf/utils.py", line 40, in rdf_dumper
[Fri Sep 09 14:09:20 2016] [error]     return _rdf_dumper(provider, None)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_rdf/utils.py", line 79, in _rdf_dumper
[Fri Sep 09 14:09:20 2016] [error]     c = provider.get_by_id(id)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 184, in go
[Fri Sep 09 14:09:20 2016] [error]     parent_object.session.commit()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 788, in commit
[Fri Sep 09 14:09:20 2016] [error]     self.transaction.commit()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 384, in commit
[Fri Sep 09 14:09:20 2016] [error]     self._prepare_impl()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 353, in _prepare_impl
[Fri Sep 09 14:09:20 2016] [error]     self.session.dispatch.before_commit(self.session)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 260, in __call__
[Fri Sep 09 14:09:20 2016] [error]     fn(*args, **kw)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 248, in before_commit
[Fri Sep 09 14:09:20 2016] [error]     "Transaction must be committed using the transaction manager"
[Fri Sep 09 14:09:20 2016] [error] AssertionError: Transaction must be committed using the transaction manager
[Fri Sep 09 14:09:20 2016] [error] 2016-09-09 14:09:20,697 ERROR [atramhasis.views.exception_views][Dummy-1] A transaction is already begun.  Use subtransactions=True to allow subtransactions.
[Fri Sep 09 14:09:20 2016] [error] Traceback (most recent call last):
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
[Fri Sep 09 14:09:20 2016] [error]     response = handler(request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 95, in tm_tween
[Fri Sep 09 14:09:20 2016] [error]     reraise(*exc_info)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 76, in tm_tween
[Fri Sep 09 14:09:20 2016] [error]     response = handler(request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
[Fri Sep 09 14:09:20 2016] [error]     response = view_callable(context, request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
[Fri Sep 09 14:09:20 2016] [error]     result = view(context, request)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/pyramid/config/views.py", line 477, in _class_requestonly_view
[Fri Sep 09 14:09:20 2016] [error]     response = getattr(inst, attr)()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/atramhasis/views/rdf.py", line 37, in rdf_full_export_turtle
[Fri Sep 09 14:09:20 2016] [error]     graph = utils.rdf_dumper(self.provider)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_rdf/utils.py", line 40, in rdf_dumper
[Fri Sep 09 14:09:20 2016] [error]     return _rdf_dumper(provider, None)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_rdf/utils.py", line 79, in _rdf_dumper
[Fri Sep 09 14:09:20 2016] [error]     c = provider.get_by_id(id)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 191, in go
[Fri Sep 09 14:09:20 2016] [error]     parent_object.session.close()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1039, in close
[Fri Sep 09 14:09:20 2016] [error]     self._close_impl(invalidate=False)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1078, in _close_impl
[Fri Sep 09 14:09:20 2016] [error]     transaction.close(invalidate)
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 466, in close
[Fri Sep 09 14:09:20 2016] [error]     self.session.begin()
[Fri Sep 09 14:09:20 2016] [error]   File "/var/projects/thesaurus/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 715, in begin
[Fri Sep 09 14:09:20 2016] [error]     "A transaction is already begun.  Use "
[Fri Sep 09 14:09:20 2016] [error] InvalidRequestError: A transaction is already begun.  Use subtransactions=True to allow subtransactions.
```

Think the whole approach of adding providers to the central registry is not working out. Similar conclusion in #296. Not sure what the alternative is though.

**Comment by koenedaele** [comment]
Wonder if we need to redesign the registry concept. To discuss IRL.

**Comment by koenedaele** [comment]
Closing this one as a duplicate of #346
