### ISSUE TITLE
Installing demo on server

### ISSUE THREAD

**Issue by fvepwc** [OnroerendErfgoed/atramhasis#428]
Hi all,

I'm installing the demo on a remote server (linux) now, following the directions on http://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site

When running `pip install -r requirements-dev.txt`, I get following error:

```
Collecting pyramid==1.7.6 (from -r atramhasis-requirements.txt (line 2))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached pyramid-1.7.6-py2.py3-none-any.whl
Collecting pyramid-tm==1.0 (from -r atramhasis-requirements.txt (line 3))
  Using cached pyramid_tm-1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pyramid_rewrite==0.2 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): skosprovider==0.6.1 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): skosprovider_sqlalchemy==0.5.1 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pyramid_skosprovider==0.8.0 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): skosprovider_rdf==0.6.0 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 12))
Collecting skosprovider_getty==0.4.0 (from -r atramhasis-requirements.txt (line 14))
  Using cached skosprovider_getty-0.4.0-py2.py3-none-any.whl
Collecting skosprovider_heritagedata==0.3.0 (from -r atramhasis-requirements.txt (line 16))
  Using cached skosprovider_heritagedata-0.3.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): language-tags==0.4.3 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 20))
Collecting sqlalchemy==1.0.19 (from -r atramhasis-requirements.txt (line 23))
  Using cached SQLAlchemy-1.0.19.tar.gz
Requirement already satisfied (use --upgrade to upgrade): zope.sqlalchemy==0.7.7 in /usr/local/lib/python2.7/dist-packages (from -r atramhasis-requirements.txt (line 24))
Collecting transaction==1.6.1 (from -r atramhasis-requirements.txt (line 25))
  Using cached transaction-1.6.1.tar.gz
Collecting psycopg2==2.6.2 (from -r atramhasis-requirements.txt (line 26))
  Using cached psycopg2-2.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wvatHH/psycopg2/
```

I tried continuing the installation process, which went reasonably well.
The next issue I encounter is then at `dump_rdf development.ini`, which throws

```
Traceback (most recent call last):
  File "/usr/local/bin/dump_rdf", line 9, in <module>
    load_entry_point('atramhasis', 'console_scripts', 'dump_rdf')()
  File "/usr/local/lib/python2.7/dist-packages/atramhasis/scripts/dump_rdf.py", line 55, in main
    env = bootstrap(config_uri)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/paster.py", line 107, in bootstrap
    app = get_app(config_uri, options=options)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/paster.py", line 28, in get_app
    return loader.get_wsgi_app(name, options)
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/admin/Burgerloket/Atramhasis/atramhasis_demo/atramhasis_demo/__init__.py", line 38, in main
    config.include('atramhasis')
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/__init__.py", line 839, in include
    c(configurator)
  File "/usr/local/lib/python2.7/dist-packages/atramhasis/__init__.py", line 23, in includeme
    config.scan()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/__init__.py", line 1043, in scan
    ignore=ignore)
  File "/usr/local/lib/python2.7/dist-packages/venusian/__init__.py", line 204, in scan
    for importer, modname, ispkg in results:
  File "/usr/local/lib/python2.7/dist-packages/venusian/__init__.py", line 403, in walk_packages
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/atramhasis/skos/__init__.py", line 11, in <module>
    from cachecontrol import CacheControl
ImportError: No module named cachecontrol
```

I get a similar error when trying to run `pserve development.ini`. Any idea what may have gone wrong?

I'm using python 2.7.3 and pip 8.1.2

Best,
Frederik

**Comment by koenedaele** [comment]
The first error has to do with building postgres libraries. If you're on a Debian based server (such a Ubuntu), you probably need to do: apt-get install libpq-dev. When we install on a server we install the following Debian packages:

```bash
$ apt-get install python-software-properties
$ apt-get install python-dev libffi-dev
$ apt-get install libpq-dev
$ apt-get install supervisor (only when running on nginx)
$ apt-get install libxml2-dev
$ apt-get install libraptor2-dev
$ apt-get install nodejs-legacy (only for LDF)
$ apt-get install npm (only for LDF)
$ npm install -g ldf-server (only for LDF)
```

We also install nginx.

After you've installed all those packages, you would need to run `pip install -r requirements-dev.txt` again.

**Comment by koenedaele** [comment]
The missing cachecontrol is caused by not being able to install `psycopg`. Please fix that error first and continue installing.

**Comment by koenedaele** [comment]
Are you sure you've installed libpq-dev? What does the following command tell you?

```bash
$ dpkg --get-selections | grep libpq
```

**Comment by fvepwc** [comment]
It returns

`libpq5:amd64                                    install`

Maybe good to mention that during the installation there were often issues getting the archives. I do not know whether this voids the installation or can be ignored.

Output for `apt-get install libpq-dev`

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  icedtea-netx icedtea-netx-common
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpq5
Suggested packages:
  postgresql-doc-9.6
The following NEW packages will be installed:
  libpq-dev
The following packages will be upgraded:
  libpq5
1 upgraded, 1 newly installed, 0 to remove and 194 not upgraded.
Need to get 341 kB of archives.
After this operation, 949 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Err http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg/main libpq5 amd64 9.6.3-1.pgdg70+1
  404  Not Found [IP: 217.196.149.55 80]
Err http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg/main libpq-dev amd64 9.6.3-1.pgdg70+1
  404  Not Found [IP: 217.196.149.55 80]
Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-9.6/libpq5_9.6.3-1.pgdg70+1_amd64.deb  404  Not Found [IP: 217.196.149.55 80]
Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-9.6/libpq-dev_9.6.3-1.pgdg70+1_amd64.deb  404  Not Found [IP: 217.196.149.55 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by koenedaele** [comment]
That does not look like it shoud. I think you should contact your hosting provider.

**Comment by jensscheerlinck** [comment]
In the end this was a simple to fix dependency issues:
- Server was already running PostgreSQL 10.1
- Updated psycopg2 dependency in requirements.txt to latest version resolved the error

**Comment by koenedaele** [comment]
If you upgrade to Atramhasis 0.6.4, things should be ok. That version packages psycopg2 2.7.3.1
