### ISSUE TITLE
Issues with demo & production install

### ISSUE THREAD

**Issue by 3kynox** [OnroerendErfgoed/atramhasis#515]
Hello everyones,

I'm getting difficulty to get atramhasis_demo or a production installation running.
For the demo part, I'm following the docs at https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site

First error occur at initialize_atramhasis_db development.ini command:
```
/atramhasis_demo$ sudo initialize_atramhasis_db development.ini
Traceback (most recent call last):
  File "/usr/local/bin/initialize_atramhasis_db", line 11, in <module>
    load_entry_point('atramhasis', 'console_scripts', 'initialize_atramhasis_db')()
  File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/nox/.local/lib/python2.7/site-packages/atramhasis/scripts/initializedb.py", line 14, in <module>
    from zope.sqlalchemy import ZopeTransactionExtension
ImportError: cannot import name ZopeTransactionExtension
```

I tried using default sqlite alchemy.url and using postgre connection strings with an effective created database on my postgre server. I used these connection strings:
- sqlalchemy.url = postgresql://this:is_secret@localhost:5432/atramhasis_demo
sqlalchemy.url = postgresql+psycopg2://this:is_secret@localhost:5432/atramhasis_demo
---

Different errors from a production install where steps are explained here: https://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project

I followed the same database configuration as above and at the moment to run the server with pserve...

```
/my_thesaurus$ pserve development.ini 
Traceback (most recent call last):
  File "/usr/local/bin/pserve", line 11, in <module>
    load_entry_point('pyramid', 'console_scripts', 'pserve')()
  File "/home/nox/.local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 34, in main
    return command.run()
  File "/home/nox/.local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 275, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/nox/.local/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line 129, in get_wsgi_app
    global_conf=defaults,
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 277, in loadobj
    global_conf=global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
    global_conf=global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 459, in get_context
    section)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 481, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 412, in get_context
    global_conf=global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
    global_conf=global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 625, in get_context
    object_type, name=name)
  File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 645, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'my_thesaurus' distribution was not found and is required by the application
```

I tried with python2.7 & python 3.6 (on ubuntu, we're using `python pserve pcreate` commands for python 2.7 and `python3 pserve3 pcreate3` for python 3 commands).

No more luck...

Ubuntu 18.04 used here.

Thanks for the help in advance :)

**Comment by koenedaele** [comment]
> Hello everyones,
> 
> I'm getting difficulty to get atramhasis_demo or a production installation running.
> For the demo part, I'm following the docs at https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site
> 
> First error occur at initialize_atramhasis_db development.ini command:
> 
> ```
> /atramhasis_demo$ sudo initialize_atramhasis_db development.ini
> Traceback (most recent call last):
>   File "/usr/local/bin/initialize_atramhasis_db", line 11, in <module>
>     load_entry_point('atramhasis', 'console_scripts', 'initialize_atramhasis_db')()
>   File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
>     return ep.load()
>   File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
>     return self.resolve()
>   File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/nox/.local/lib/python2.7/site-packages/atramhasis/scripts/initializedb.py", line 14, in <module>
>     from zope.sqlalchemy import ZopeTransactionExtension
> ImportError: cannot import name ZopeTransactionExtension
> ```
> 
> I tried using default sqlite alchemy.url and using postgre connection strings with an effective created database on my postgre server. I used these connection strings:
> 
> * sqlalchemy.url = postgresql://this:is_secret@localhost:5432/atramhasis_demo
>   sqlalchemy.url = postgresql+psycopg2://this:is_secret@localhost:5432/atramhasis_demo

This issue is due to an update to zope.sqlalchemy. Reverting to zope.sqlachemy 1.1 fixes this. We're working on a new release where we'll update to the newest dependency.

**Comment by koenedaele** [comment]
> Different errors from a production install where steps are explained here: https://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project
> 
> I followed the same database configuration as above and at the moment to run the server with pserve...
> 
> ```
> /my_thesaurus$ pserve development.ini 
> Traceback (most recent call last):
>   File "/usr/local/bin/pserve", line 11, in <module>
>     load_entry_point('pyramid', 'console_scripts', 'pserve')()
>   File "/home/nox/.local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 34, in main
>     return command.run()
>   File "/home/nox/.local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 275, in run
>     app = loader.get_wsgi_app(app_name, config_vars)
>   File "/home/nox/.local/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line 129, in get_wsgi_app
>     global_conf=defaults,
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
>     return loadobj(APP, uri, name=name, **kw)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 277, in loadobj
>     global_conf=global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
>     global_conf=global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 326, in _loadconfig
>     return loader.get_context(object_type, name, global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 459, in get_context
>     section)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 481, in _context_from_use
>     object_type, name=use, global_conf=global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 412, in get_context
>     global_conf=global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
>     global_conf=global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
>     return loader.get_context(object_type, name, global_conf)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 625, in get_context
>     object_type, name=name)
>   File "/home/nox/.local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 645, in find_egg_entry_point
>     pkg_resources.require(self.spec)
>   File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/home/nox/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'my_thesaurus' distribution was not found and is required by the application
> ```
> 
> I tried with python2.7 & python 3.6 (on ubuntu, we're using `python pserve pcreate` commands for python 2.7 and `python3 pserve3 pcreate3` for python 3 commands).
> 
> No more luck...
> 
> Ubuntu 18.04 used here.
> 
> Thanks for the help in advance :)

To fix this one, run python setup.py develop before you run pserve.

**Comment by 3kynox** [comment]
Thanks, it helped a lot!

For the demo part, reverting zope.sqlalchemy worked like a charm.
For the production part, I had to `sudo python3 setup.py develop`. Also, how to come back in production mode? Because I look like in dev and stability could be lowered?

Last one, any documentation around to get this working using Apache or / NgInx?

**Comment by koenedaele** [comment]
It seems very strange that you had to run that command (python3 setup.py develop) as sudo. I think that means you're installing globally?

> Also, how to come back in production mode? Because I look like in dev and stability could be lowered?

I don't understand this question

> Last one, any documentation around to get this working using Apache or / NgInx?

Our instance (https://thesaurus.onroerenderfgoed.be) is running on Nginx + gunicorn I believe. Main thing to pay attention to is to run the current (0.6.x) version single-threaded. We're improving this in 0.7.0, but for now you should not run it with mutiple threads.

**Comment by 3kynox** [comment]
Hello!

1. The sudo command was only for that specific "...setup.py develop" command, the others have been ran without sudo, so yes it's strange but could be probably related to my debian host system.

2. This misunderstood question about how to return to production environment is related to the "python3 setup.py develop" command that (from my understanding) pull the develop branch, which make me saying we're in a no-production environment. So I was asking how to be in a real production env? But if it's the right way, that's okay.

3. Okay for usage of Gunicorn, I'm currently reading their documentation. Any further guide? Or at least the differences to take care between atramhasis installation instructions and the required steps with Nginx / Gunicorn?

Thanks again :)

**Comment by 3kynox** [comment]
Update: trying to install the demo on my debian server raise this:

```
(atramhasis_demo) sh-4.4$ pserve development.ini 
Traceback (most recent call last):
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/bin/pserve", line 11, in <module>
    load_entry_point('pyramid', 'console_scripts', 'pserve')()
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 34, in main
    return command.run()
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 275, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/plaster_pastedeploy/__init__.py", line 129, in get_wsgi_app
    global_conf=defaults,
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/util.py", line 58, in fix_call
    reraise(*exc_info)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/compat.py", line 32, in reraise
    raise e.with_traceback(tb)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/var/www/vhosts/araa.pt/atramhasis.araa.pt/atramhasis_demo/atramhasis_demo/__init__.py", line 42, in main
    config.include('atramhasis_demo.skos')
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/pyramid/config/__init__.py", line 676, in include
    c(configurator)
  File "/var/www/vhosts/araa.pt/atramhasis.araa.pt/atramhasis_demo/atramhasis_demo/skos/__init__.py", line 177, in includeme
    skosregis.register_provider(TREES)
  File "/var/www/vhosts/araa.pt/Env/atramhasis_demo/lib/python3.5/site-packages/skosprovider/registry.py", line 98, in register_provider
    if self.instance_scope not in provider.allowed_instance_scopes:
TypeError: argument of type 'NoneType' is not iterable
```

I suspect a package with a wrong version but feeling lost.

**Comment by Wim-De-Clercq** [comment]
These were my required steps following the demo from the docs:
```
$ mkvirtualenv atramhasis_demo
$ pip install -U atramhasis

=EXTRA=========================================
$ pip install pyramid-skosprovider==0.8.0
$ pip install zope.sqlalchemy==1.1
$ pip install skosprovider-sqlalchemy==0.5.2
=For the optional dump_rdf step ===============
$ pip install cachecontrol   
$ pip install bleach
=END OPTIONAL==================================
=END EXTRA=====================================

$ pcreate -s atramhasis_demo atramhasis_demo
# Follow the rest of the docs.
```
The upcoming release will fix these most likely, but I do wonder if we should release a minor release to take care of the version conflicts immediately.

**Comment by cedrikv** [comment]
Hy @3kynox ,
Version 0.7.0 was just released, if you still have issues you might want to check that one. It has some big changes, and will hopefully fix all your problems.
