### ISSUE TITLE
Error in initialize_db script

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#609]
Executing the initialize_db script in the demo scaffold I get this error (both python 2 and python 3 venvs):

```
2020-10-01 14:06:31,064 INFO  [sqlalchemy.engine.base.Engine][MainThread] COMMIT
Traceback (most recent call last):
  File "/home/koen/.virtualenvs/atdemo07027/bin/initialize_atramhasis_db", line 11, in <module>
    load_entry_point('atramhasis', 'console_scripts', 'initialize_atramhasis_db')()
  File "/home/koen/.virtualenvs/atdemo07027/local/lib/python2.7/site-packages/atramhasis/scripts/initializedb.py", line 141, in main
    db_session.commit()
  File "/home/koen/.virtualenvs/atdemo07027/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/koen/.virtualenvs/atdemo07027/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/koen/.virtualenvs/atdemo07027/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/home/koen/.virtualenvs/atdemo07027/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/home/koen/.virtualenvs/atdemo07027/local/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 263, in before_commit
    "Transaction must be committed using the transaction manager"
AssertionError: Transaction must be committed using the transaction manager
```

But the data is present in the db after executing the command, so I think the transaction manager already commited those sessions.

**Comment by cedrikv** [comment]
on what branch were you testing?

**Comment by koenedaele** [comment]
Develop

**Comment by cedrikv** [comment]
I think we should wait till after the merge of #509 to resolve this issue
