### ISSUE TITLE
Can't run created project

### ISSUE THREAD

**Issue by mallox007** [OnroerendErfgoed/atramhasis#643]
A project created by following the documentation at https://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project won't start due to the following error:

```
Traceback (most recent call last):
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\pyramid\config\__init__.py", line 646, in include
    c = getattr(module, 'includeme')
AttributeError: module 'my_thesaurus.skos' has no attribute 'includeme'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Projects\thesaurus\thesaurus\Scripts\pserve-script.py", line 11, in <module>
    load_entry_point('pyramid', 'console_scripts', 'pserve')()
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\pyramid\scripts\pserve.py", line 34, in main
    return command.run()
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\pyramid\scripts\pserve.py", line 275, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\plaster_pastedeploy\__init__.py", line 125, in get_wsgi_app
    return loadapp(
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\paste\deploy\loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\paste\deploy\loadwsgi.py", line 278, in loadobj
    return context.create()
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\paste\deploy\loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\paste\deploy\loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\paste\deploy\util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "c:\users\user\projects\thesaurus\thesaurus\my_thesaurus\my_thesaurus\__init__.py", line 41, in main
    config.include('my_thesaurus.skos')
  File "C:\Users\user\Projects\thesaurus\thesaurus\lib\site-packages\pyramid\config\__init__.py", line 648, in include
    raise ConfigurationError(
pyramid.exceptions.ConfigurationError: module 'my_thesaurus.skos' has no attribute 'includeme'
(thesaurus)
```

Anything i'm doing wrong?
Starting the application without using a scaffold works without issue.

**Comment by goessebr** [comment]
Hi @mallox007 

Sorry for the late answer. This repo has been idle for a while.

The demo project is now using cookiecutter to create a new (demo) project from a scaffold. There are some problems with the setup however that will be tackled in #696. We will update the documentation in the coming weeks.
