### ISSUE TITLE
ImportError: cannot import name 'default_handlers' from 'openapi_spec_validator'

### ISSUE THREAD

**Issue by MPParsley** [OnroerendErfgoed/atramhasis#733]
When running the python server the following error is thrown:

```
atramhasis_demo % pserve development.ini   
Traceback (most recent call last):
  File "/usr/local/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pyramid/scripts/pserve.py", line 30, in main
    return command.run()
  File "/usr/local/lib/python3.9/site-packages/pyramid/scripts/pserve.py", line 271, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/local/lib/python3.9/site-packages/plaster_pastedeploy/__init__.py", line 125, in get_wsgi_app
    return loadapp(
  File "/usr/local/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
  File "/usr/local/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python3.9/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python3.9/site-packages/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
  File "/Volumes/webdev/www/district09/opendata/atramhasis_demo/atramhasis_demo/__init__.py", line 38, in main
    config.include("atramhasis")
  File "/usr/local/lib/python3.9/site-packages/pyramid/config/__init__.py", line 666, in include
    c(configurator)
  File "/usr/local/lib/python3.9/site-packages/atramhasis/__init__.py", line 18, in includeme
    config.include("pyramid_openapi3")
  File "/usr/local/lib/python3.9/site-packages/pyramid/config/__init__.py", line 632, in include
    c = self.maybe_dotted(callable)
  File "/usr/local/lib/python3.9/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/usr/local/lib/python3.9/site-packages/pyramid/path.py", line 327, in maybe_resolve
    return self._resolve(dotted, package)
  File "/usr/local/lib/python3.9/site-packages/pyramid/path.py", line 334, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/usr/local/lib/python3.9/site-packages/pyramid/path.py", line 383, in _zope_dottedname_style
    found = __import__(used)
  File "/usr/local/lib/python3.9/site-packages/pyramid_openapi3/__init__.py", line 3, in <module>
    from .exceptions import extract_errors
  File "/usr/local/lib/python3.9/site-packages/pyramid_openapi3/exceptions.py", line 3, in <module>
    from openapi_core.schema.exceptions import OpenAPIError
  File "/usr/local/lib/python3.9/site-packages/openapi_core/__init__.py", line 3, in <module>
    from openapi_core.shortcuts import (
  File "/usr/local/lib/python3.9/site-packages/openapi_core/shortcuts.py", line 3, in <module>
    from openapi_core.schema.shortcuts import create_spec
  File "/usr/local/lib/python3.9/site-packages/openapi_core/schema/shortcuts.py", line 3, in <module>
    from openapi_spec_validator import (
ImportError: cannot import name 'default_handlers' from 'openapi_spec_validator' (/usr/local/lib/python3.9/site-packages/openapi_spec_validator/__init__.py)
```

**Comment by MPParsley** [comment]
See https://github.com/Pylons/pyramid_openapi3/issues/173

**Comment by koenedaele** [comment]
How did you install? The latest version (1.2.0) has openapi-spec-validator==0.4.0 in the requirements file. Did you try a different version?

**Comment by MPParsley** [comment]
@koenedaele, I installed as documented on
- https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site-with-cookiecutter
- https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter/blob/main/README.rst

There are slight differences between both documentations.

**Comment by koenedaele** [comment]
@Wim-De-Clercq Is this still an issue with v2?

**Comment by Wim-De-Clercq** [comment]
The v2 branch has this feature https://github.com/OnroerendErfgoed/atramhasis/pull/784 so the `jinja2` and `markupsafe` requirements will be fine with that. 
The `openapi-spec-validator==0.4.0` should already be part of atramhasis since 1.3.0.
The `pyramid_openapi3` requirement is already part of atramhasis since 1.1.0.

However, due to https://github.com/Pylons/pyramid_openapi3/pull/206 we may want to already restrict it to `<0.17` because that's definitely going to break things.
