### ISSUE TITLE
Non-numeric id's - backend

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#739]

**Comment by Wim-De-Clercq** [comment]
> Add atramhasis.id_generation_strategy to skosproviders metadata. When none is provided, assume numeric as the default to maintain BC

This seems like a default in the Skosprovider repo then?

**Comment by koenedaele** [comment]
No, skosprovider itself is readonly and never generates ID's. Only Atramhasis generates ID's. The skosprovider metadata is nothing more than a place to store configuration in a single place, per thesaurus. Just like we already store an _atramhasis.force_display_label_language_ there.

So, around https://github.com/OnroerendErfgoed/atramhasis/blob/55a24f8f09ff6b490c8e39e3b407f892463674e5/atramhasis/views/crud.py#L167 something like:

```
generation_strategy = skosprovider.metadata.get('atramhasis.id_generation_strategy', 'numeric')
if generation_strategey == 'guid':
 #generate GUID 
 pass
elif generation_strategy == 'manual':
#get from request
 pass
else:
 #generate numeric
 pass
```

**Comment by Wim-De-Clercq** [comment]
Do we keep backwards compatibility for the "id" in the JSON response?
Because it's a string in the database, by default all responses will contain concepts/collections with string ids. Even if it is a number.
So the question is, do we parse these back to a number if the related provider has numeric generation?

Same for the requests. Do we still support integer IDs as input? And provider imports, ...

**Comment by koenedaele** [comment]
We've bumped the version number to 2.0.0, so we're doing breaking changes anyway. So, we don't have to be gentle.

When we import from a skos-file, it's possible that we get something like:
`
<dc:identifier rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">3</dc:identifier>
`

This tells us it's actually a number. but actually, this could be datatype http://www.w3.org/TR/xmlschema11-2/#date as well. Basically, it seems like the simplest solution is casting whatever is set in dct:identifier to a String. Having id be numeric for some things and string for others sounds like a big hassle. Because then it would be int in the JSON response, but still be stored as str in the db. So, sorting the search result as int would be more difficult. And suppose some decides to switch the generation strategy from int to guid, then the id's will change from int to str anyway.

 So I'm fine with handling and validating everything as a string, sounds simplest.

**Comment by koenedaele** [comment]
Skosprovider_sqlalchemy 2.0.0 has been released

**Comment by cedrikv** [comment]
I have an error doing the '/providers' call:
```
023-03-13 11:34:37,130 ERROR [atramhasis.views.exception_views][waitress-0] 'NoneType' object has no attribute 'pattern'
Traceback (most recent call last):
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid_openapi3/__init__.py", line 133, in wrapper_view
    return view(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 450, in rendered_view
    response = view_renderer.render_view(
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/renderers.py", line 443, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/renderers.py", line 466, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/renderers.py", line 462, in render
    result = renderer(value, system_values)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/renderers.py", line 276, in _render
    return self.serializer(value, default=default, **self.kw)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/renderers.py", line 291, in default
    return result(obj, request)
  File "/home/vandercf/git/atramhasis/atramhasis/renderers.py", line 208, in provider_adapter
    'uri_pattern': provider.uri_generator.pattern,
AttributeError: 'NoneType' object has no attribute 'pattern'
2023-03-13 11:34:37,139 INFO  [pyramid_debugtoolbar][waitress-0] Squashed AttributeError at http://0.0.0.0:6543/providers
traceback url: http://0.0.0.0:6543/_debug_toolbar/313430333237323439373835373630/exception

```

the error is triggered on the AAT provider (doesnt have a uri_generator)
![image](https://user-images.githubusercontent.com/1849458/224678190-285c6284-35a7-4284-89ec-890ec2924cd2.png)

**Comment by cedrikv** [comment]
Also error on POST:
```
2023-03-13 14:47:22,930 ERROR [atramhasis.views.exception_views][waitress-2] 'concept_id'
Traceback (most recent call last):
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/home/vandercf/git/atramhasis/.venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 129, in _class_view
    response = getattr(inst, attr)()
  File "/home/vandercf/git/atramhasis/atramhasis/utils.py", line 92, in advice
    return fn(parent_object, *args, **kw)
  File "/home/vandercf/git/atramhasis/atramhasis/views/crud.py", line 177, in add_concept
    concept.concept_id = validated_json_concept["concept_id"]
KeyError: 'concept_id'
2023-03-13 14:47:22,931 INFO  [pyramid_debugtoolbar][waitress-2] Squashed KeyError at http://local.onroerenderfgoed.be:6543/conceptschemes/STUFF/c
traceback url: http://local.onroerenderfgoed.be:6543/_debug_toolbar/313430353131363737323434373034/exception

```


Payload:
![image](https://user-images.githubusercontent.com/1849458/224721699-9f44a46b-0abb-4e79-95e7-209f1b7e93db.png)
```json
{"id":"één","concept_scheme":"STUFF","type":"concept","labels":[{"language":"nl-BE","type":"prefLabel","label":"ding 1","id":0.3604983301195783}],"notes":[],"sources":[],"related":[],"narrower":[],"broader":[],"subordinate_arrays":[],"member_of":[],"matches":{}}
```

**Comment by cedrikv** [comment]
@Wim-De-Clercq another problem with editing concepts in a MANUAL id generator conceptscheme:
PUT on a non numeric id gives a 404 error
PUT an a numeric id gives a 400 error:
> [{id: "3 already exists."}]
message: "Concept could not be validated"

![image](https://user-images.githubusercontent.com/1849458/225621582-5f11a4c7-d902-404d-b5ed-e41da19fccf8.png)

**Comment by cedrikv** [comment]
everything works now as expected
