### ISSUE TITLE
Can't run demo

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#746]
When running the dump_rdf command I get the following:

```
(atramhasis_demo)$ dump_rdf development.ini 
Traceback (most recent call last):
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/config/actions.py", line 307, in execute_actions
    callable(*args, **kw)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid_jinja2/__init__.py", line 449, in register
    env = create_environment_from_options(env_opts, loader_opts)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid_jinja2/__init__.py", line 401, in create_environment_from_options
    env = Environment(loader=loader, **env_opts)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'with_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/koen/.virtualenvs/atramhasis_demo/bin/dump_rdf", line 8, in <module>
    sys.exit(main())
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/atramhasis/scripts/dump_rdf.py", line 49, in main
    env = bootstrap(config_uri)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/paster.py", line 117, in bootstrap
    app = get_app(config_uri, options=options)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/paster.py", line 30, in get_app
    return loader.get_wsgi_app(name, options)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/plaster_pastedeploy/__init__.py", line 111, in get_wsgi_app
    return loadapp(
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 273, in loadobj
    return context.create()
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 741, in create
    return self.object_type.invoke(self)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/paste/deploy/loadwsgi.py", line 138, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/paste/deploy/util.py", line 61, in fix_call
    val = callable(*args, **kw)
  File "/home/koen/Projecten/python/skos/atramhasis_demo/atramhasis_demo/__init__.py", line 53, in main
    return config.make_wsgi_app()
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/config/__init__.py", line 891, in make_wsgi_app
    self.commit()
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/config/actions.py", line 151, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/config/actions.py", line 311, in execute_actions
    reraise(
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/util.py", line 732, in reraise
    raise value.with_traceback(tb)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid/config/actions.py", line 307, in execute_actions
    callable(*args, **kw)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid_jinja2/__init__.py", line 449, in register
    env = create_environment_from_options(env_opts, loader_opts)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid_jinja2/__init__.py", line 401, in create_environment_from_options
    env = Environment(loader=loader, **env_opts)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
pyramid.exceptions.ConfigurationExecutionError: <class 'AttributeError'>: module 'jinja2.ext' has no attribute 'with_'
  in:
  Line 488 of file /home/koen/.virtualenvs/atramhasis_demo/lib/python3.10/site-packages/pyramid_jinja2/__init__.py:
    config.add_jinja2_renderer(".jinja2", package=package)
```

Steps to reproduce:
- Follow the instructions at https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site-with-cookiecutter up until the dump_rdf point
- If I skip the dump_rdf command, the error arrises when running pserve

**Comment by koenedaele** [comment]
Same as #733

**Comment by Wim-De-Clercq** [comment]
And also fixed in https://github.com/OnroerendErfgoed/atramhasis/issues/749
At least until the jinja 3 upgrade comes.
