### ISSUE TITLE
A GET /conceptschemes REST call is not possible when an external provider is not available

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/atramhasis#850]
Using:
```
atramhasis 1.1.0
pyramid-skosprovider==1.1.0
skosprovider==1.1.1
skosprovider-getty==1.0.0
skosprovider-rdf==1.0.0
skosprovider-sqlalchemy==1.0.0
```

An external provider http://vocab.getty.edu that we are using was down for some time. A request to http://vocab.getty.edu gave us a 503 response. During that time it was not possible to use our admin section because at the startup of the admin section there is a REST call to get the JSON representation of GET /conceptschemes

```
2023-08-23 14:40:56,863 ERROR [atramhasis.views.exception_views][MainThread] Request could not be executed due to server issues - Request: http://vocab.getty.edu/aat/.rdf. Response: b'<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'.
Traceback (most recent call last):
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 319, in secured_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid/viewderivers.py", line 129, in _class_view
    response = getattr(inst, attr)()
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/atramhasis/views/crud.py", line 128, in get_conceptschemes
    return ProviderView(self.request).get_conceptschemes()
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid_skosprovider/views.py", line 135, in get_conceptschemes
    return [
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/pyramid_skosprovider/views.py", line 140, in <listcomp>
    'uri': p.concept_scheme.uri,
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/skosprovider_getty/providers.py", line 71, in concept_scheme
    self._conceptscheme = self._get_concept_scheme()
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/skosprovider_getty/providers.py", line 75, in _get_concept_scheme
    return conceptscheme_from_uri(
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/skosprovider_getty/utils.py", line 43, in conceptscheme_from_uri
    graph = uri_to_graph('%s.rdf' % (conceptscheme_uri), session=s)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/skosprovider_getty/utils.py", line 300, in uri_to_graph
    res = do_get_request(uri, s)
  File "/var/projects/thesaurus/venv/lib/python3.8/site-packages/skosprovider_getty/utils.py", line 317, in do_get_request
    raise ProviderUnavailableException(
skosprovider.exceptions.ProviderUnavailableException: Request could not be executed due to server issues - Request: http://vocab.getty.edu/aat/.rdf. Response: b'<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'.
```

Is this something we can avoid?

**Comment by koenedaele** [comment]
I'm not sure why the admin view calls the /conceptschemes endpoint, but when I do, I only see the following data on the AAT:

```
"type": "skos:ConceptScheme",
		"id": "AAT",
		"uri": "http://vocab.getty.edu/aat/",
		"label": "Art and Architecture Thesaurus",
		"subject": [
			"external"
		]
```

These data ar generated at https://github.com/OnroerendErfgoed/pyramid_skosprovider/blob/develop/pyramid_skosprovider/views.py#L142-L143

Only two things are generated from the conceptscheme: the conceptscheme uri and a label. The first (conceptscheme uri) can actually be generated from a call to p.get_vocabulary_uri, which has actually been the prefered way fort a while now. So, the pyramid_skosprovider view should call this.

However, that still leaves us without a solution for the label. However, I think we could try to load the conceptscheme and if that fails, fall back to the URI for the label. I think we're actually doing that somewhere in Atramhasis already for conceptschemes without a label.

So, I believe a few changes to pyramid_skosprovider could solve this issue in a way that the call to /conceptschemes can return something relevant. Not sure if this will not cause further issues somewhere else in the admin interface.

**Comment by koenedaele** [comment]
Upon further inspection, it does seem the Getty services only provide a single label for a conceptscheme. So it seems a bit stupid to call the service to get a single label that's quite predictable.

**Comment by koenedaele** [comment]
Updating pyramid_skosprovider to 1.2.1 should fix this. We'll add another fix to skosprovider_getty to make it more robust for all usecases.
