### ISSUE TITLE
object has none attribute 'group' 

### ISSUE THREAD

**Issue by DavideLicheri** [OnroerendErfgoed/atramhasis#918]
Hi,
trying to delete a concept, I've this unexpected server error:

Traceback (most recent call last):
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/config/views.py", line 151, in __call__
    return view(context, request)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/atramhasis/utils.py", line 100, in advice
    return fn(parent_object, *args, **kw)
  File "/home/amministratore/Envs/my_atramhasis/lib/python3.10/site-packages/atramhasis/protected_resources.py", line 33, in advice
    scheme_id = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Probably I've some problem with the manual ID,  that is "/prova/subprova"...

Thanks!
davide

**Comment by koenedaele** [comment]
Hi Davide,

This is triggered by the protected operation decorator mentioned in https://atramhasis.readthedocs.io/en/latest/customisation.html#foreign-keys

This is a decorator that emits a "ProtectedResourceEvent" to signal something is happening with a concept. By default this happens when someone tries to invoke the delete concept action on a concept. To trigger this Event, the request is analysed to see which concept in wich conceptscheme is being triggered by checking out the path. This is normally something like /conceptscheme/SCHEME_ID/c/CONCEPT_ID. I think this means you have tried rewriting the URL paths to something other than this? Is that correct?

**Comment by DavideLicheri** [comment]
Hi Koenedaele,
yes! 
you are in right: I wrote a manual ID like "/prova/subprova", so that Atramhasis translate in a URI like ".../codes//prova/subprova".
But a doubled slash is an obvious syntax mistake and will be deleted triggering the decorator.
Thanks!

**Comment by koenedaele** [comment]
I hope your issue is fixed now, let me know if there's anything else.
